# Production-grade analysis options for Flutter
# Place this file at the project root: analysis_options.yaml

include: package:flutter_lints/flutter.yaml

analyzer:
  # Exclude generated/build files from analysis
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.pb.dart"
    - "**/*.pbjson.dart"
    - "**/*.template.dart"
    - "**/build/**"
    - "**/.dart_tool/**"
    - "**/generated/**"

  # Treat specific issues as errors or warnings
  errors:
    dead_code: error
    unused_local_variable: warning
    invalid_assignment: error
    invalid_override: error
    missing_required_param: error
    unused_field: warning
    todo: info

  # Add analyzer plugins
  plugins:
    - dart_code_metrics

linter:
  rules:
    # Core best practices
    - always_declare_return_types
    - always_specify_types
    - avoid_annotating_with_dynamic
    - prefer_final_fields
    - prefer_final_locals
    - prefer_single_quotes
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_is_empty
    - prefer_is_not_empty
    - use_key_in_widget_constructors
    - annotate_overrides
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_dynamic_calls
    - prefer_if_null_operators
    - prefer_expression_function_bodies
    - sort_constructors_first
    - constant_identifier_names
    - non_constant_identifier_names

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    lines-of-code: 300
    number-of-parameters: 6
  metrics-exclude:
    - "**/*.g.dart"
    - "**/generated/**"
  rules:
    - avoid-empty-catches
    - no-boolean-literal-compare

# Relaxed rules for tests
overrides:
  - include: package:flutter_lints/flutter.yaml
    files: "test/**"
    rules:
      prefer_const_constructors: false
      avoid_print: false
      always_declare_return_types: false
